version: '3'

networks:
    network:

services:
    web:
        image: nginx:latest
        networks:
            - network
        ports:
            - "11000:80"
        volumes:
            - ./src:/src:ro
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - php
    php:
        image: docker.dyhs.kr/dy-ctf/php:7.4-fpm-alpine
        networks:
            - network
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_HOST=${DB_HOST}
        volumes:
            - ./src:/src:ro
    db:
        image: mysql:8.0
        networks:
            - network
        restart: always
        ports:
            - 10000:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./init:/docker-entrypoint-initdb.d