version: '3'

networks:
  network:

services:
  prob:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - "8001:8000"
    command:
      - /start.sh